### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by AutoDaws** [ic3w0lf22/ROBLOX_MULTI#1]
Was wondering if this works still

**Comment by bainchild** [comment]
yes

**Comment by Slippyu** [comment]
How do you use it

**Comment by UselessGamedev** [comment]
Is it safe?

**Comment by neoon112** [comment]
How do you build the DLL? Can there be a step by step.

(And how to use it)

**Comment by neoon112** [comment]
> Is it safe?

its the fucking src

**Comment by 1x6** [comment]
yes try it out

**Comment by ghost** [comment]
> its the fucking src

What is that?

**Comment by ghost** [comment]
> > its the fucking src
> 
> What is that?

it's the source.
it can't be a virus if the source of all of the code is there.
