### ISSUE TITLE
Potentially Dangerous

### ISSUE THREAD

**Issue by diamond12121** [ic3w0lf22/ROBLOX_MULTI#3]
This seems to run a background process separate from the one that's meant to be there, and while it's not obviously a virus, it's clearly doing more on my system than what is advertised. Combining this and the frequent crashes it tends to cause for me and it's simply not worth it.

**Comment by ic3w0lf22** [comment]
Can you explain more in detail what other process it's running other than ROBLOX_MULTI.exe?

**Comment by aphextwinfan82** [comment]
Its not dangerous, It barely consumes any resources for me and to my knowledge the code seems perfectly safe 🤨

**Comment by lolmanurfunny** [comment]
oooo spooky cmd prompt ui. Anyway, if someone malicious wanted to hide their malware.. they wouldn't give you the god damn source to it.

**Comment by b-risk** [comment]
why is this still open
it's like a 12 line code exe..
